"""Add expires_at to Task Table

Revision ID: 5a8724eb068b
Revises: d6cc61217372
Create Date: 2024-12-03 18:30:13.108887+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8724eb068b'
down_revision: Union[str, None] = 'd6cc61217372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_table', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # 既存のレコードの expires_at カラムに値を設定
    op.execute("UPDATE task_table SET expires_at = '1970-01-01 00:00:00'")

    # expires_at カラムに NOT NULL 制約を追加
    op.alter_column('task_table', 'expires_at', nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_table', 'expires_at')
    # ### end Alembic commands ###
