"""Update User Table

Revision ID: fb68cd6914c1
Revises: 5a8724eb068b
Create Date: 2024-12-07 23:11:46.673088+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb68cd6914c1'
down_revision: Union[str, None] = '5a8724eb068b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ロール事前定義
    op.execute("CREATE TYPE role AS ENUM ('ADMIN', 'USER')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False))
    op.add_column('user_table', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_table', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_table', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('user_table_mail_key', 'user_table', type_='unique')
    op.create_unique_constraint(None, 'user_table', ['email'])
    op.drop_column('user_table', 'mail')
    op.drop_column('user_table', 'password')
    op.drop_column('user_table', 'token')
    op.drop_column('user_table', 'token_expires')
    op.drop_column('user_table', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ロール削除
    op.execute("DROP TYPE role")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_table', type_='unique')
    op.create_unique_constraint('user_table_mail_key', 'user_table', ['mail'])
    op.drop_column('user_table', 'updated_at')
    op.drop_column('user_table', 'created_at')
    op.drop_column('user_table', 'is_active')
    op.drop_column('user_table', 'role')
    op.drop_column('user_table', 'hashed_password')
    op.drop_column('user_table', 'email')
    op.drop_column('user_table', 'user_name')
    # ### end Alembic commands ###
